version: '3.3'
services:

  producer:
    build: .
    image: xefiji/dblogger    
    depends_on:       
      - rabbitmq
    networks:
      - db
      - rabbitmq
    ports:
      - ${PRODUCER_PORT}:${PRODUCER_PORT}
    environment: 
      WAIT_HOSTS: rabbitmq:${RABBITMQ_PORT}
      WAIT_BEFORE_HOSTS: 10

  consumer:    
    image: xefiji/dblogger
    command: sh -c "/wait && ./binlog --mode=consume --exchange=binlog_internal"
    depends_on: 
      - producer
      - rabbitmq      
      - es01
      - es02
    networks: 
      - rabbitmq
      - elastic
    ports:
      - ${CONSUMER_PORT}:${CONSUMER_PORT}
    environment: 
      WAIT_HOSTS: rabbitmq:${RABBITMQ_PORT}, es01:9200
      WAIT_BEFORE_HOSTS: 30

  rabbitmq:
    image: rabbitmq:3-management-alpine  
    environment:
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=${RABBITMQ_VM_MEMORY_HIGH_WATERMARK:-.50}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST:-rabbitmq}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-admin}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:?}

    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - ${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}
    networks:      
      - rabbitmq


  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    ports:
      - 9201:9201
    networks:
      - elastic
      
  kib01:
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION}
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=${ELASTICSEARCH_CONTAINER_URL}
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_CONTAINER_URL}
    networks:
      - elastic
    
volumes:
  data01:
    driver: local
  data02:
    driver: local  

networks:  
  db:    
  rabbitmq:
  elastic:
    driver: bridge