version: '3.3'
services:

  adminer:
    image: adminer
    ports:
      - 8080:8080

  db:
    image: mysql:5.7
    command: --log-bin --server-id=1 #important: enable  mysqlbinlogs
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      TZ: '${DB_TIMEZONE}'
    ports:
      - '${DB_PORT}:${DB_PORT}'
    expose:
      - '${DB_PORT}'
    volumes:
      - my-db:/var/lib/mysql
    
volumes:
  my-db: